# Petri net configurations
petrinet.0=exampleHuang.properties
petrinet.1=travelAgencySystem.properties
petrinet.number=1

# Maximum number of invariants per execution
execution.max_invariants=186

# Decision policies (probabilities)
policies.is_balanced=true
policies.balanced=0.5
policies.reservation_confirmation=0.8
policies.agent_priority_p6=0.75

tree.fullprint=false