# Petri net configurations
petrinet.0=exampleHuang.properties
petrinet.1=travelAgencySystem.properties
petrinet.number=1

# Maximum number of invariants per execution
execution.max_invariants=186

# Decision policies (probabilities)
policies.enable=true
policies.standard=0.5
policies.value.1=0.8
policies.value.2=0.75

tree.fullprint=true